### ISSUE TITLE
Blocked by CORS policy

### ISSUE THREAD

**Issue by code-504** [yakovkhalinsky/backblaze-b2#104]
I put the keys in the app and also in Backblaze bucket i configure cors with all origins and in google console:

`Access to XMLHttpRequest at 'https://api.backblazeb2.com/b2api/v2/b2_authorize_account' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by code-504** [comment]
Use this API in front end doesn't work, is in the back end. I think that one solution is creating funtions in a server like node js funtions and return the data to your front end with JavaScript.

**Comment by code-504** [comment]
@pjatx BackBlaze never worked for me on the front end. It's weird because once I saw an example with BackBlaze with JavaScript (I can't remember where from) and it only used JavaScript on the front-end and it worked and also what you comment, BackBlaze API doesn't return the correct headers. The documentation about BackBlaze API is very poor.

**Comment by mattwelke** [comment]
@code-504 Maybe [this](https://github.com/mattwelke/upload-file-to-backblaze-b2-from-browser-example) was the example you saw?

(don't mind me, came here after playing with Chat GPT where it recommended using this library in a unit test I plan to write for my example)
