### ISSUE TITLE
axios in package.json in npm package still 0.18

### ISSUE THREAD

**Issue by Benny739** [yakovkhalinsky/backblaze-b2#108]
The axios version in the package.json of the released package is still 0.18. This always leads to npm complaining about security issues. Setting this to 0.21.1 would be cool.

**Comment by SayakMukhopadhyay** [comment]
Please release the current master to NPM as the existing latest as a vulnerable dependency.

**Comment by zacharytyhacz** [comment]
@yakovkhalinsky

**Comment by chasenstark** [comment]
@yakovkhalinsky Please release current master to NPM. The existing NPM package still has axios 0.18 as a dependency.

**Comment by odensc** [comment]
Published to npm as 1.7.0. Sorry for the delay everybody, busy year.
