### ISSUE TITLE
How do I get the url of my uploaded image?

### ISSUE THREAD

**Issue by mattfrancis888** [yakovkhalinsky/backblaze-b2#116]
Hey all,

I'm trying to upload a file to b2 and then store that uploaded file's URL in my database so I can refer to it.
As the docs said, [b2_get_upload_url](https://www.backblaze.com/b2/docs/b2_get_upload_url.html) gives an upload URL that will be used before uploading.
```
        {    

        "bucketId" : "4a48fe8875c6214145260818",     

        "uploadUrl" : "https://pod-000-1005-03.backblaze.com/b2api/v2/b2_upload_file?cvt=c001_v0001005_t0027&bucket=4a48fe8875c6214145260818",    

            "authorizationToken" :  
        "2_20151009170037_f504a0f39a0f4e657337e624_9754dde94359bd7b8f1445c8f4cc1a231a33f714_upld" 

        }
```

However, when I try to access uploadUrl, I receive:
```
        {"code": "method_not_allowed", 
        "message": "method not allowed: GET", 
        "status": 405 }

```
**I also notice that  my image in my b2 uses other links such as:**
https://f002.backblazeb2.com/file/werwerw/thomasRhett.jpg

https://werwerwer.s21.us-west-0222.backblazeb2.com/thomasRhett.jpg

https://f002.backblazeb2.com/b2api/v1/b2_download_file_by_id?fileId=werwerwerwerwerm0050

So how can I actually access my new image's URL?

Thanks! Any help would be appreciated :)

**Comment by poacher2k** [comment]
The URL returned is not to be used _before_ uploading, but _for_ uploading. Use the `uploadUrl` and the `authorizationToken` to upload your image with a `POST` request.

See https://www.backblaze.com/b2/docs/b2_upload_file.html for more details

**Comment by metadaddy** [comment]
You can construct the download URL according to the mechanism documented at [b2_download_file_by_name](https://www.backblaze.com/b2/docs/b2_download_file_by_name.html):

> The base URL to use comes from the b2_authorize_account call, and looks something like https://f345.backblazeb2.com. The "f" in the URL stands for "file", and the number is the cluster number containing your account. To this base, you add "file/", your bucket name, a "/", and then the name of the file. The file name may itself include more "/" characters.
> 
> If you have a bucket named "photos", and a file called "cute/kitten.jpg", then the URL for downloading that file would be: https://f345.backblazeb2.com/file/photos/cute/kitten.jpg.

In terms of backblaze-b2, this is simply:

    const auth = await b2.authorize();
    const downloadURL = auth.data.downloadUrl + '/file/' + bucketName + '/' + fileName;

**Comment by varundeva** [comment]
Same issue i have..
i can able to upload file, i have to store download url somewhere in database

**Comment by metadaddy** [comment]
@varundeva Read [my comment](https://github.com/yakovkhalinsky/backblaze-b2/issues/116#issuecomment-1007084232) immediately above yours. You don't need anything from the B2 response to create the download URL.
