### ISSUE TITLE
Get download url

### ISSUE THREAD

**Issue by expertsa** [yakovkhalinsky/backblaze-b2#12]
Is it possible to get file download url or do I have to download on server and handle downloadUrl my self?

**Comment by yakovkhalinsky** [comment]
I'm assuming you are wanting the file download URL.

You could do this a few of ways. One way is to use the file's ID or combine both the bucket name and the filename.

First thing you need to do would be to get the base download URL from the auth command.
`b2.auth()`

From the auth response you s:
```
{
    accountId: '...',
    apiUrl: '...',
    downloadUrl: 'https://z000.backblaze.com'
}
```

You should probably cache this somewhere so you don't need to run `b2.auth()` just to get it.

Then if you know the bucket name and you know the filename you just pull them together like so:
```
var baseDownloadUrl = authRespose.downloadUrl;
var bucketName = 'foo';
var fileName = 'beep-boop.png';
var fullDownloadUrl = [ 
    baseDownloadUrl,
    bucketName,
    fileName
].join('/');
``` 

To give you `https://z000.backblaze.com/foo/beep-boop.png`

Or if you have the file's ID, which you could get from uploading the file using `b2.uploadFile(...)`.

E.g. from the uploadResponse like so:
```
{
    ...
    fileId: 'abcd234987324babdsakjhdasdsaa-dhkfhjkad`
    ...
}
```

Pull together a string like this:
Then if you know the bucket name and you know the filename you just pull them together like so:
```
var baseDownloadUrl = authRespose.downloadUrl;
var fileId = uploadResponse.fileId;
var fullDownloadUrl = [ 
    baseDownloadUrl,
    'b2api',
    'v1',
    'b2_download_file_by_id?' + fileId
].join('/');
``` 

Should give you something like:
`https://z000.backblaze.com/b2api/v2/b2_download_file_by_id?abcd234987324babdsakjhdasdsaa-dhkfhjkad`

**Comment by yakovkhalinsky** [comment]
Does that answer your question @expertsa ?

**Comment by expertsa** [comment]
Thank you very much, it's perfectly clear !

**Comment by expertsa** [comment]
Sorry to bother you again, do you know why those url are showing me the file instead of downloading it?
I mean I know that right click save as can make it but if I a user wants to download 6 files, it's easier if he just have to click on download rather than right clicking on each files and save as.

I hope it's possible, or maybe this will be possible after Beta.

**Comment by yakovkhalinsky** [comment]
I'll have a look at how the download URL's work later today and I'll post my
findings here :)

> On Feb 16 2016, at 1:26 am, Expert SA &lt;notifications@github.com&gt;
wrote:  

>

> Sorry to bother you again, do you know why those url are showing me the file
instead of downloading it?  
I mean I know that right click save as can make it but if I a user wants to
download 6 files, it's easier if he just have to click on download rather than
right clicking on each files and save as.

>

> I hope it's possible, or maybe this will be possible after Beta.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/yakovkh
alinsky/backblaze-b2/issues/12#issuecomment-184227862).![](https://github.com/
notifications/beacon/AAnbxm2PFiD9lrKLiRCENoje_YjfDfmNks5pkdd5gaJpZM4HZJZy.gif)

**Comment by yakovkhalinsky** [comment]
@expertsa as far as I can tell, unless you send the mime type as an octet-stream, the browser will try and open it.

Here is a great article about the HTML5 `download` attribute: 
https://davidwalsh.name/download-attribute

That might help you with your problem.

**Comment by expertsa** [comment]
Hi, thanks, working like a charm with the download attribute.

**Comment by jamiesyme** [comment]
@yakovkhalinsky Are you open to the idea of exposing a function for this? Specifically: https://github.com/yakovkhalinsky/backblaze-b2/blob/master/lib/actions/file.js#L261

The example you gave above isn't very complicated, but it'd be far more convenient to write something like:

```javascript
await b2.authorize();
const url = await b2.getFileDownloadUrl(fileId);
```

**Comment by jamiesyme** [comment]
For future reference, the example code for downloading a file by `fileId` in the above comment has a bug in the query string.

The corrected code looks like:

```javascript
var baseDownloadUrl = authResponse.downloadUrl;
var fileId = uploadResponse.fileId;
var fullDownloadUrl = [ 
    baseDownloadUrl,
    'b2api',
    'v1',
    'b2_download_file_by_id?fileId=' + fileId
].join('/');
```
