### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by ADumaine** [yakovkhalinsky/backblaze-b2#126]
It has been a year since the last issue was closed.

**Comment by Firfi** [comment]
bump

**Comment by Firfi** [comment]
> b

ackblaze

**Comment by yakovkhalinsky** [comment]
This library was opened sourced from day one, I came to a time where I couldn't individually put the time in the keep it going, and then several gracious contributors stepped up to continue to maintain it.

If you use it and want to see it updated, consider showing some graciousness like the previous contributors and bring a PR or even offer to become a contributor, especially if you use this library.

**Comment by Firfi** [comment]
Thank you for the update. I'm sorry that the thread comments looked ungracious to you. I'm sure nobody meant to be rude here.
