### ISSUE TITLE
Upload progress

### ISSUE THREAD

**Issue by tutankhamen-1** [yakovkhalinsky/backblaze-b2#18]
Is there any way to know how much data has been uploaded?

**Comment by yakovkhalinsky** [comment]
You should see a `contentLength` property in the response of `b2.uploadFile()` which is in bytes

**Comment by tutankhamen-1** [comment]
I should have been more specific. I'm trying to monitor it in real time in order to build a progress bar.

**Comment by yakovkhalinsky** [comment]
Not sure you could do that until the module supports multipart uploading.

The upload is a single request to the B2 service with the whole file.

**Comment by crazyscience** [comment]
PR is on the way, folks.

**Comment by crazyscience** [comment]
#21 adds support for progress notifications via `deferred.notify()`. If it ever merges in, you'll be able to get upload/download/request progress via the third parameter of `.then()` as such:
```
b2.someCommand().then(
  function(res) { /* success handler */ },
  function(err) { /* error handler */ },
  function(info) { /* progress handler (called many times) */ }
);
```

**Comment by yakovkhalinsky** [comment]
Good work again from @crazyscience 👍

**Comment by crazyscience** [comment]
The above only worked for v0.9.12 and only worked for download progress reporting. We've changed how progress reporting is handled to take into account both the request (for uploads) and the response (for downloads). As of `v1.0.0`, a callback function can be passed into relevant `b2.method()`s. See the `README` for more information and usage examples. For large, multipart uploads, you will have to write your own code to aggregate across the multiple requests.

**Comment by odensc** [comment]
This should now be supported with `onUploadProgress` so I'll close. Please reopen if this is still an issue.
