### ISSUE TITLE
SHA1 checksum 

### ISSUE THREAD

**Issue by HeikoMueller** [yakovkhalinsky/backblaze-b2#19]
Hi.
I was trying to use the module for uploading files within an Electron app, but when uploading a file, I constantly encountered an issue with the SHA1 checksum:

{code: "bad_request", message: "sha1 is wrong length", status: 400}

Any ideas how to solve that?
Thank's a lot
Heiko

**Comment by Dayjo** [comment]
Hello, 

I'm also having the same issue, I'm also using Electron.

**Comment by yakovkhalinsky** [comment]
Fix coming up shortly 👍 

PR soon to be merged
