### ISSUE TITLE
internal error 'bz_sha1 did not match data received' on b2.uploadFile

### ISSUE THREAD

**Issue by tennysonholloway** [yakovkhalinsky/backblaze-b2#2]
I'm not sure if this error is the fault of this package, or the b2 API. I'm just trying to upload a file to a bucket, but it seems that it's failing because the sha1 didn't match up with what the server received. 

I'm unsure if I am able to provide a sha1, or if the library is doing this for me. 

Here is the code:
```javascript
b2.authorize().then( /* authorized */
    (response) => {
        b2.getUploadUrl(bucket).then( /* get url to upload to */
                (response) => {
                    fs.readFile('test.mp3', 'utf8', (err, data) => { /* get data object from fs */
                        b2.uploadFile( { /* upload data to bucket */
                            uploadUrl: response.uploadUrl,
                            uploadAuthToken: response.authorizationToken,
                            filename: 'test.mp3',
                            data: data /* maybe a problem? */
                        }).then(
                            (response) => {console.log(response)},
                            (err) => {console.log(err)} /* error gets logged here )': */
                        );
                    });
                },
                (error) => { console.log(error); }
        );
    },
    (error) => { console.log(error); }
);
```

**Comment by yakovkhalinsky** [comment]
Thanks @tennysonholloway for trying out the library.

When I get home from work (~ 8hrs from now), I'll reply with the code snippet I used to read out the file data when I tested the function.

Could just be that the `uploadFile()` is expecting something different in `data`. So it could be just a matter of bad documentation on my part :smiley_cat:

**Comment by yakovkhalinsky** [comment]
@tennysonholloway when I tested this I use the following:
`var data = fs.readFileSync('/Users/foo/Desktop/test/test.png');`

I passed `data` string in from that.

**Comment by tennysonholloway** [comment]
Ok, I will try that. I wonder why it doesn't work with the async file read. Oh well (:

Thanks for the responses.

**Comment by tennysonholloway** [comment]
I found the error. When I passed 'utf8' into `readFile` it doesn't return the raw buffer, it returns an encoded string, which makes the sha1 different. Removing it made my original code work.

**Comment by yakovkhalinsky** [comment]
Nice! I'll mark this as a question so people can find it in future :+1:
