### ISSUE TITLE
[question] Delete all file in folder or starting with /folderName 

### ISSUE THREAD

**Issue by billouboq** [yakovkhalinsky/backblaze-b2#26]
Hi,

Sorry to ask this here, but b2 is new so not a lot of people are responding on stackoverflow.

Do you know any solution to delete all files in a folder (so with name starting with "folder/") ?

I guess I have to do a listFile starting with "folderUrl" and then for each file a delete file version call.

**Comment by jaredreich** [comment]
@billouboq you can get all the files with `listFileNames` (passing the `bucketId` param), then filter those files that start with the `folder_name/` you want, then loop through them and for each one perform the `deleteFileVersion` (passing the `fileId` and `fileName` params)

**Comment by odensc** [comment]
As @jaredreich said, that's probably the best way to do it! If you have an issues with that method please reopen.
