### ISSUE TITLE
Use the library with a stream

### ISSUE THREAD

**Issue by mayeaux** [yakovkhalinsky/backblaze-b2#32]
There's no docs relating to streams, are they able to be used with this library?

**Comment by jaredreich** [comment]
@mayeaux you should be able to use this library with streams. Maybe dig deeper into the Node.js docs, axios (or whatever http library) docs, and B2 API docs.

**Comment by jamiesyme** [comment]
I was curious about using streams as well, and while it seems that axios supports them, I don't think this library does (at least for uploading).

On upload, it tries to [generate a SHA1 hash](https://github.com/yakovkhalinsky/backblaze-b2/blob/master/lib/actions/file.js#L23), but the sha1 library [doesn't seem to support streams](https://github.com/pvorb/node-sha1/blob/master/sha1.js#L7]).

I can think of a few fixes:

- Convert the stream to a buffer and hash that (but then what's the point of using a stream)
- Set the `X-Bz-Content-Sha1` header to `do_not_verify` (probably a bad idea)
- Set the `X-Bz-Content-Sha1` header to `hex_digits_at_end` and hash the contents as the request is uploaded (based on [this page](https://www.backblaze.com/b2/docs/uploading.html), it's not recommend, but possible)
- Let the user supply the hash as an optional parameter to `b2.uploadFile()`

**Comment by yakovkhalinsky** [comment]
Interesting discussion, I haven't put much though into it since the inception of this library.

I feel like that last option of providing the hash might be a nicer option, which would result in something less opinionated in terms implementation.

Either way, I'm open to PR's for this feature.

**Comment by odensc** [comment]
Should be possible now in `v1.4.0` using `contentLength` and `hash`.

**Comment by dbismut** [comment]
Hi @odensc thanks for the lib. Would you be able to explain how use the lib with streams? I've seen this lib here that looks like it does the job, is this the recommended way of proceeding?
