### ISSUE TITLE
Implement `b2_get_download_authorization` operation

### ISSUE THREAD

**Issue by jaredreich** [yakovkhalinsky/backblaze-b2#35]
Hi there @yakovkhalinsky! Thanks so much for your work on this lib!

What are the chances of adding a method for the `b2_get_download_authorization` operation? Looks like it's listed in the API docs, but not available in this lib.

API link: https://www.backblaze.com/b2/docs/b2_get_download_authorization.html

I just did a run-through of all the available operations, and this is the only one that's missing, as of 2017-11-14.

**Comment by yakovkhalinsky** [comment]
Thanks @jaredreich for your question.

I'm a bit short on time these days, but I'm happy to take pull requests and open the repo to more contributors 👍

**Comment by jaredreich** [comment]
PR: https://github.com/yakovkhalinsky/backblaze-b2/pull/37

**Comment by jaredreich** [comment]
@yakovkhalinsky PR: https://github.com/yakovkhalinsky/backblaze-b2/pull/37

**Comment by jaredreich** [comment]
Added in #37
