### ISSUE TITLE
Looking for contributors

### ISSUE THREAD

**Issue by yakovkhalinsky** [yakovkhalinsky/backblaze-b2#36]
I am open to anyone who would like to contribute, I can add any interested parties to the repo and the npm library.

**Comment by cbess** [comment]
@yakovkhalinsky I'm interested in contributing.

**Comment by yakovkhalinsky** [comment]
Thanks @cbess can you email me your details at yakov at therocketsurgeon dot com?

**Comment by odensc** [comment]
I'm up to help as well. I recently signed up to B2 for one of my projects and I'd like to contribute some features such as TypeScript typings.

**Comment by yakovkhalinsky** [comment]
Just posting in here, I've been in touch with @realhidden who has confirmed they are still interested in helping maintain this package :+1:

**Comment by yakovkhalinsky** [comment]
I've done a quick wiki page to document how to deal with version bumping for npm publishing:
https://github.com/yakovkhalinsky/backblaze-b2/wiki/Creating-a-new-NPM-release

**Comment by Amit-A** [comment]
@yakovkhalinsky I'm also interested in contributing.

**Comment by yakovkhalinsky** [comment]
Thanks @Amit-A have replied to your email

**Comment by yakovkhalinsky** [comment]
@Amit-A once you've accepted on github I will add you in npm :+1:
