### ISSUE TITLE
Retry options already builtin anywhere

### ISSUE THREAD

**Issue by RyanQuey** [yakovkhalinsky/backblaze-b2#41]
Hello, 

Thanks for this project, have used it already with great satisfaction thus far. 

I'm wondering though: is there anyway to pass in an option and retry on failure? I'm specifically wanting to 
retry once or maybe twice if I get a 503, service_unavailable

**Comment by yakovkhalinsky** [comment]
Thanks for the question @RyanQuey unfortunately not at this time.

It is something I would like to add in the future though.

**Comment by Amit-A** [comment]
I think this can be done easily with the [axios-retry](https://github.com/softonic/axios-retry) module. If I can get it to work, I will submit a pull request.

**Comment by Amit-A** [comment]
[This pull request](https://github.com/yakovkhalinsky/backblaze-b2/pull/61) should do it.

**Comment by haywirez** [comment]
@Amit-A thanks!

**Comment by Amit-A** [comment]
Merged #61 which does this. Will make an NPM release soon as #62 is merged.
