### ISSUE TITLE
Feature Request: X-Bz-Info

### ISSUE THREAD

**Issue by mmccallum** [yakovkhalinsky/backblaze-b2#5]
Any plans to support setting X-Bz-Info headers?

Thanks!

**Comment by yakovkhalinsky** [comment]
Thanks for the suggestion @mmccallum definitely something I would like to add :+1: 

I'll have a look at the API docs over the next day or so and see what I can do :dart:

**Comment by yakovkhalinsky** [comment]
@mmccallum will be adding this in the next few days :+1:

**Comment by yakovkhalinsky** [comment]
@mmccallum just a quick update.

I've got a PR ready to go, but I am confirming some things with the Backblaze guys as I am having some HTTP 500 errors in certain cases, maybe due to an undocumented character limit.

Once I confirm all these details about these headers I'll merge and publish.

**Comment by yakovkhalinsky** [comment]
Closing as PR #6 has been merged to master.

Will be in npm registry shortly :dancers:

**Comment by mmccallum** [comment]
Thanks!  Will give this a try later this week and report any issues.

**Comment by mmccallum** [comment]
Works like a charm so far!  Thanks.  I think this will help others as well.  
I'm going to post another request as well that you may want to add.
