### ISSUE TITLE
Retag Pull Requests for 1.1.0 release

### ISSUE THREAD

**Issue by yakovkhalinsky** [yakovkhalinsky/backblaze-b2#57]
@cbess @odensc @realhidden 

Just putting this in so we can clean up for an npm release.

I think since we've tagged some PR's already for 1.1.0, we should move those that aren't in 1.0.4 into the 1.1.0 release in preparation for making a changelog and doing the final version bump.

This would go a long way to refresh the package.

**Comment by odensc** [comment]
Sounds good to me. I've moved the PRs into 1.1.0 so we should be ready to make a changelog. Definitely should get this out soon so the npm package doesn't say last published a year ago :)

**Comment by cbess** [comment]
@odensc agreed :)

**Comment by cbess** [comment]
@yakovkhalinsky It doesn't matter much to me, but I'll give it a try.

**Comment by yakovkhalinsky** [comment]
Cool, closing this issue then, all yours @cbess 
Final task is to bump the version and update the change log :+1:

**Comment by odensc** [comment]
@cbess Any updates? :)

**Comment by cbess** [comment]
@odensc The goal for me is to handle it over the weekend.

**Comment by yakovkhalinsky** [comment]
Sounds good @cbess let us know if you need anything :+1:

**Comment by cbess** [comment]
tagged and npm package released

**Comment by cbess** [comment]
Soli Deo gloria

**Comment by yakovkhalinsky** [comment]
Nice one! Thanks again for all your help guys :+1:
