### ISSUE TITLE
Calling authorize second time always fails when application credentials are used

### ISSUE THREAD

**Issue by phil-r** [yakovkhalinsky/backblaze-b2#66]
Calling authorize second time fails when application credentials are used, because `b2.accountId` gets re-written with actual accountId.

Related to #64

**Comment by phil-r** [comment]
I've submitted a patch for it: #67
Meanwhile you can use `npm i @phil-r/backblaze-b2` with 

```js
const b2 = new B2({
    applicationKeyId: 'applicationKeyId', // instead of accountId
    applicationKey: 'applicationKey'
})
```

**Comment by davidsonsns** [comment]
waiting for @yakovkhalinsky about your pull @phil-r. Tks
