### ISSUE TITLE
onUploadProgress is never called

### ISSUE THREAD

**Issue by andrelec1** [yakovkhalinsky/backblaze-b2#69]
my code look like : 
```js 
const uploadPartObj = {
          partNumber: orderedChunks[i + 1].id,
          uploadUrl: tokenInfo.data.uploadUrl,
          uploadAuthToken: tokenInfo.data.authorizationToken,
          data: orderedChunks[i + 1].buffer,
          hash: orderedChunks[i + 1].sha1,
          onUploadProgress: (event) => console.log(event),
        };
await this.#b2.uploadPart(uploadPartObj);
```

but i never see the console.log, the onUploadProgress is never trigger ...

**Comment by odensc** [comment]
Hi - `onUploadProgress` is provided by Axios, which only supports upload progress in browsers. (see axios/axios#1793)

You could make a (less accurate) progress bar by calculating the percentage of parts uploaded. (e.g. `numParts / numPartsUploaded`)

If you'd like to submit a feature request for this to work in Node, feel free but it's unlikely to be possible without replacing Axios in the library.

Hope this helps.
